const ENV = (typeof import.meta !== "undefined" && import.meta.env) || {};
export const API_BASE_URL = ENV.VITE_API_BASE_URL || "https://xiaoguaishou.zachariahi.xyz";
export const API_LOGIN = "/index.php/Api/Yonghu/login";
export const API_TELMS = "/index.php/Api/Yonghu/telms";
export const API_LOGOUT = "/index.php/Api/Yonghu/logout";
export const API_USER_CREATE = "/index.php/Api/Yonghu/setYonghu";
export const API_USER_LIST = "/index.php/Api/Yonghu/getYonghuList";
export const API_USER_LIST_N = "/index.php/Api/Yonghu/getYonghuListN";
export const API_USER_LIST_NII = "/index.php/Api/Yonghu/getYonghuListNII";
export const API_USER_GET = "/index.php/Api/Yonghu/getYonghu";
export const API_USER_DELETE = "/index.php/Api/Yonghu/delYonghu";
export const API_ROLE_LIST = "/index.php/Api/Yonghu/getRoleListN";
export const API_ROLE_LIST_MANAGE = "/index.php/Api/Yonghu/getRoleList";
export const API_ROLE_SET = "/index.php/Api/Yonghu/setRole";
export const API_ROLE_DEL = "/index.php/Api/Yonghu/delRole";
export const API_ROLE_GET = "/index.php/Api/Yonghu/getRole";
export const API_ORDER_LIST = "/index.php/Api/Order/getOdersList";
export const API_ORDER_GRAPH_LIST = "/index.php/Api/Home/graphOrderList";
export const API_ORDER_DATA = "/index.php/Api/Order/orderData";
export const API_ORDER_GET = "/index.php/Api/Order/getOrder";
export const API_ORDER_CHARGES_LIST = "/index.php/Api/Order/getListallcharges";
export const API_ORDER_EXPORT = "/index.php/Api/Order/exportData";
export const API_ORDER_EXPORT_TEMPLATE = "/index.php/Api/Order/exportTemplate";
export const API_ORDER_UPLOAD_EXCEL = "/index.php/api/Order/uploadExcel";
export const API_ORDER_UPDATE_LOGISTICS = "/index.php/Api/Order/UpOder";
export const API_ORDER_RISK_LEVEL = "/index.php/Api/Order/getRisklevel";
export const API_STRIPE_LIST = "/index.php/Api/Stripe/getStripeList";
export const API_STRIPE_LIST_ALL = "/index.php/Api/Stripe/getStripeListN";
export const API_STRIPE_CREATE = "/index.php/Api/Stripe/setStripe";
export const API_STRIPE_DELETE = "/index.php/Api/Stripe/delStripe";
export const API_STRIPE_LOG_LIST = "/index.php/Api/Stripe/getStripeLogList";
export const API_STRIPE_WARNING_LIST = "/index.php/Api/Stripe/getEarlyFraudWarnings";
export const API_STRIPE_DISPUTE_LIST = "/index.php/Api/Stripe/getDisputelist";
export const API_STRIPE_GROUP_CREATE = "/index.php/Api/Stripe/setPaygroup";
export const API_STRIPE_GROUP_LIST = "/index.php/Api/Stripe/getPaygroupList";
export const API_STRIPE_GROUP_LIST_N = "/index.php/Api/Stripe/getPaygroupListN";
export const API_STRIPE_GROUP_GET = "/index.php/Api/Stripe/getPaygroup";
export const API_STRIPE_GROUP_DELETE = "/index.php/Api/Stripe/delPaygroup";
export const API_COUNTRY_LIST = "/index.php/Api/Country/getCountryListN";
export const API_COUNTRY_GROUP_LIST = "/index.php/Api/Country/getCountrygroupList";
export const API_COUNTRY_GROUP_LIST_N = "/index.php/Api/Country/getCountrygroupListN";
export const API_COUNTRY_GROUP_GET = "/index.php/Api/Country/getCountrygroup";
export const API_COUNTRY_GROUP_CREATE = "/index.php/Api/Country/setCountrygroup";
export const API_COUNTRY_GROUP_DELETE = "/index.php/Api/Country/delCountrygroup";
export const API_UPLOAD = "/api/common/upload";
export const API_EMAIL_TYPE_CREATE = "/index.php/Api/Advanced/setEmailtype";
export const API_EMAIL_TYPE_LIST = "/index.php/Api/Advanced/getEmailtypeList";
export const API_EMAIL_TYPE_LIST_N = "/index.php/Api/Advanced/getEmailtypeListN";
export const API_EMAIL_TYPE_GET = "/index.php/Api/Advanced/getEmailtype";
export const API_EMAIL_TYPE_DELETE = "/index.php/Api/Advanced/delEmailtype";
export const API_EMAIL_TEMPLATE_CREATE = "/index.php/Api/Advanced/setEmailTemplate";
export const API_EMAIL_TEMPLATE_LIST = "/index.php/Api/Advanced/getEmailTemplateList";
export const API_EMAIL_TEMPLATE_GET = "/index.php/Api/Advanced/getEmailTemplate";
export const API_EMAIL_TEMPLATE_DELETE = "/index.php/Api/Advanced/delEmailTemplate";
export const API_EMAIL_TEMPLATE_LIST_N = "/index.php/Api/Advanced/getEmailTemplateListN";
export const API_EMAIL_SET_TASK = "/index.php/Api/Advanced/setEmailtask";
export const API_EMAIL_TASK_LIST = "/index.php/Api/Advanced/getEmailtaskList";
export const API_EMAIL_TASK_GET = "/index.php/Api/Advanced/getEmailtask";
export const API_EMAIL_TASK_DELETE = "/index.php/Api/Advanced/delEmailtask";
export const API_SMTP_SET = "/index.php/Api/Advanced/setSmtp";
export const API_SMTP_LIST = "/index.php/Api/Advanced/getSmtpList";
export const API_SMTP_GET = "/index.php/Api/Advanced/getSmtp";
export const API_SMTP_DELETE = "/index.php/Api/Advanced/delSmtp";

// Blacklist APIs
export const API_BLACKLIST_CREATE = "/index.php/Api/Heimingdan/setHeimingdan";
export const API_BLACKLIST_LIST = "/index.php/Api/Heimingdan/getHeimingdanList";
export const API_BLACKLIST_GET = "/index.php/Api/Heimingdan/getHeimingdan";
export const API_BLACKLIST_DELETE = "/index.php/Api/Heimingdan/delHeimingdan";
export const API_CONTACT_US = "/index.php/Api/Home/contactUs";

// Account Type (Product Category) APIs
export const API_ACCOUNT_TYPE_SET = "/index.php/api/Account/setAccountType";
export const API_ACCOUNT_TYPE_LIST = "/index.php/api/Account/getAccountTypeList";
export const API_ACCOUNT_TYPE_LIST_N = "/index.php/api/Account/getAccountTypeListN";
export const API_ACCOUNT_TYPE_GET = "/index.php/api/Account/getAccountType";
export const API_ACCOUNT_TYPE_DELETE = "/index.php/api/Account/delAccountType";

// Account Product Name (BSite Product) APIs
export const API_ACCOUNT_PRODUCT_SET = "/index.php/api/Account/setAccountProductName";
export const API_ACCOUNT_PRODUCT_LIST = "/index.php/api/Account/getAccountProductNameList";
export const API_ACCOUNT_PRODUCT_GET = "/index.php/api/Account/getAccountProductName";
export const API_ACCOUNT_PRODUCT_DELETE = "/index.php/api/Account/delAccountProductName";
export const API_ACCOUNT_EXPORT_TEMPLATE = "/index.php/Api/Account/exportTemplate";
export const API_ACCOUNT_UPLOAD_EXCEL = "/index.php/api/Account/uploadExcel";

// Website Management APIs
export const API_WEBSITE_SET = "/index.php/Api/Website/setWebsite";
export const API_WEBSITE_LIST = "/index.php/Api/Website/getWebsiteList";
export const API_WEBSITE_GET = "/index.php/Api/Website/getWebsite";
export const API_WEBSITE_DELETE = "/index.php/Api/Website/delWebsite";
export const API_WEBSITE_EXPORT_TEMPLATE = "/index.php/Api/Website/exportTemplate";
export const API_WEBSITE_UPLOAD_EXCEL = "/index.php/api/Website/uploadExcel";
export const API_WEBSITE_BATCH_UPDATE = "/index.php/Api/Website/plWebsite";
